name: Tag to Release
description: >-
  Generate a GitHub release using an annotated tag for the release info
branding:
  icon: tag
  color: green
inputs:
  tag:
    description: The tag to use to create the release. Defaults to github.ref_name.
    required: true
    default: ${{ github.ref_name }}
  token:
    description: Authorized secret GitHub token. Defaults to github.token.
    required: true
    default: ${{ github.token }}
  draft:
    description: If the release should be a draft
    required: true
    default: false
  prerelease:
    description: >
      If the release should be a prerelease.
      Set to auto to use the prerelease pattern.
      Possible values: true|false|always|never|auto
    required: true
    default: false
  prerelease-pattern:
    description: The pattern to match to the tag to detect a prerelease
    required: false
    default: 'v*.*.*-*'
  dry-run:
    description: Set to true to prevent this action from creating a release
    required: true
    default: false
outputs:
  title:
    description: The title used to create the release
  body:
    description: The release notes
runs:
  using: node16
  main: 'dist/index.js'
