name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: yarn
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - name: Check Format
      run: yarn format-check
    - name: Test and generate coverage
      run: yarn test
    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Set up test tag
      run: |
        git config --global user.email "test@example.com"
        git config --global user.name "CI"
        git tag -a foo -m "My Title" -m "My Notes"
    - uses: ./
      with:
        tag: foo
        dry-run: true
        prerelease-pattern: foo
      id: release-step
    - name: Check title
      if: steps.release-step.outputs.title != 'My Title'
      run: |
        echo 'Expected "My Title" got "${{ steps.release-step.outputs.title }}"'
        exit 1
    - name: Check notes
      if: steps.release-step.outputs.body != 'My Notes'
      run: |
        echo 'Expected "My Notes" got "${{ steps.release-step.outputs.body }}"'
        exit 1
    - name: Check prerelease
      if: steps.release-step.outputs.prerelease != 'true'
      run: |
        echo 'Expected "true" got "${{ steps.release-step.outputs.prerelease }}"'
        exit 1
