name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: npm
    - run: npm ci
    - run: npm run build
    - name: Check Format
      run: npm run format-check
    - run: npm test

    - name: Set up test tag
      run: 'git tag -a foo -m "My Title" -m "My Notes"'
    - uses: ./
      with:
        tag: foo
        dry-run: true
      id: release-step
    - name: Check title
      if: steps.release-step.outputs.title != 'My Title'
      run: |
        echo 'Expected "My Title" got "${{ steps.release-step.outputs.title }}"'
        exit 1
    - name: Check notes
      if: steps.release-step.outputs.body != 'My Notes'
      run: |
        echo 'Expected "My Notes" got "${{ steps.release-step.outputs.body }}"'
        exit 1
